/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestimonialsImport } from './routes/testimonials'
import { Route as OurBeginningImport } from './routes/our-beginning'
import { Route as FeaturesImport } from './routes/features'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TestimonialsRoute = TestimonialsImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRoute,
} as any)

const OurBeginningRoute = OurBeginningImport.update({
  id: '/our-beginning',
  path: '/our-beginning',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesRoute = FeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesImport
      parentRoute: typeof rootRoute
    }
    '/our-beginning': {
      id: '/our-beginning'
      path: '/our-beginning'
      fullPath: '/our-beginning'
      preLoaderRoute: typeof OurBeginningImport
      parentRoute: typeof rootRoute
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/our-beginning': typeof OurBeginningRoute
  '/testimonials': typeof TestimonialsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/our-beginning': typeof OurBeginningRoute
  '/testimonials': typeof TestimonialsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/our-beginning': typeof OurBeginningRoute
  '/testimonials': typeof TestimonialsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/features' | '/our-beginning' | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/features' | '/our-beginning' | '/testimonials'
  id: '__root__' | '/' | '/features' | '/our-beginning' | '/testimonials'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeaturesRoute: typeof FeaturesRoute
  OurBeginningRoute: typeof OurBeginningRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeaturesRoute: FeaturesRoute,
  OurBeginningRoute: OurBeginningRoute,
  TestimonialsRoute: TestimonialsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/features",
        "/our-beginning",
        "/testimonials"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/features": {
      "filePath": "features.jsx"
    },
    "/our-beginning": {
      "filePath": "our-beginning.jsx"
    },
    "/testimonials": {
      "filePath": "testimonials.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
